name: Norminette

on: [push, pull_request]

jobs:
  norminette_job:
    runs-on: ubuntu-latest
    name: Norminette Mandatory & Bonus
    steps:
    - name: Pull Repo
      uses: actions/checkout@v2
    - name: Norminette Version
      uses: alexandregv/norminette-action@v3
      with:
        flags: '-v'
    - name: Norminette Mandatory & Bonus
      uses: alexandregv/norminette-action@v3
      with:
        flags: '*.c'
  norminette_custom:
    runs-on: ubuntu-latest
    name: Norminette Custom Code
    steps:
    - name: Pull Repo
      uses: actions/checkout@v2
    - name: Norminette Version
      uses: alexandregv/norminette-action@v3
      with:
        flags: '-v'
    - name: Norminette Custom Code
      uses: alexandregv/norminette-action@v3
      with:
        flags: 'custom gnl'
